{% set python_min = python_min|default("3.8") %}
{% set name = "pyexcel-io" %}
{% set version = "0.6.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 2c33d8df505e21a13bed585ac6ab7d30ec826a9f156b758394af5d22359bddb9

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation 

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools

  run:
    - python >={{ python_min }}
    - lml >=0.0.4

test:
  requires:
    - python {{ python_min }}
  
  imports:
    - pyexcel_io
    - pyexcel_io.database
    - pyexcel_io.database.exporters
    - pyexcel_io.database.importers
    - pyexcel_io.readers
    - pyexcel_io.writers


about:
  home: https://github.com/pyexcel/pyexcel-io
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: One interface to read and write the data in various excel formats, import the data into and export the data from databases
  description: |
    'A python library to read and write structured data in csv, zipped csv ' +
     'format and to/from databases' +
     ''
  doc_url: https://readthedocs.org/projects/pyexcel-io/
  dev_url: https://github.com/pyexcel/pyexcel-io

extra:
  recipe-maintainers:
    - williamjamir
    - nicoddemus
