{% set name = "pyexcel-io" %}
{% set version = "0.6.7" %}
{% set sha256 = "2c33d8df505e21a13bed585ac6ab7d30ec826a9f156b758394af5d22359bddb9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: python -m pip install . --no-deps --ignore-installed

requirements:
  host:
    - python >=3.6
    - pip
    - setuptools

  run:
    - python >=3.6
    - lml >=0.0.4

test:
  imports:
    - pyexcel_io
    - pyexcel_io.database
    - pyexcel_io.database.exporters
    - pyexcel_io.database.importers
    - pyexcel_io.readers
    - pyexcel_io.writers


about:
  home: https://github.com/pyexcel/pyexcel-io
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: One interface to read and write the data in various excel formats, import the data into and export the data from databases
  description: |
    'A python library to read and write structured data in csv, zipped csv ' +
     'format and to/from databases' +
     ''
  doc_url: https://readthedocs.org/projects/pyexcel-io/
  dev_url: https://github.com/pyexcel/pyexcel-io

extra:
  recipe-maintainers:
    - williamjamir
    - nicoddemus
